### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by prasannakulkarni1888** [culvr/ProwlSimplSharp#2]
I am trying this module with mentioned steps to follow but when i compile this simpl windows file, All data will get lost that i entered in the module and it gets blank

**Comment by prasannakulkarni1888** [comment]
I found error in Smpl # library file: Prowl Simpl Sharp Library. Can you check on that and help me please

**Comment by chadcolvin** [comment]
did you ever resolve this issue? if so, how? do you have the fixed file

**Comment by culvr** [comment]
To everyone with issues with module parameters, please try the following:

[https://s3.amazonaws.com/ProwlSimplSharp/ProwlSimplSharpDemo.zip](url)

**Comment by prasannakulkarni1888** [comment]
Hi Culvr,

Thank you so much and it worked.
