### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by chadcolvin** [culvr/ProwlSimplSharp#4]
every time this code gets compiled, the module loses its parameters. Any way to fix this or know what the issue is

**Comment by culvr** [comment]
Hi Chad,

Please try this and let me know if this solves your problem.

[https://s3.amazonaws.com/ProwlSimplSharp/ProwlSimplSharpDemo.zip](url)

**Comment by chadcolvin** [comment]
This link doesn’t work

**Comment by culvr** [comment]
Fixed.

**Comment by chadcolvin** [comment]
You rock. Thanks man
