### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by ddetton** [culvr/ProwlSimplSharp#5]
Downloaded and loaded this onto an MC3 running firmware MC3 Cntrl Eng [v1.501.2833.24264 (Oct 04 2016), #0070120E] @E-00107f1eae79.  Opened a Prowl account and created an API key.  Purchased the Prowl IOS app and logged into my newly created Prowl account.  Tested by sending a notification from the Prowl web site and the notification appeared on my ios device.  Pasted the API key into API KEY 1 in the test program and recompiled and loaded onto the MC3.  Launched Simpl Debugger and pulsed the send signal.  The Status_Message$ that I get back is "Connection Error."  I tried this on the example program and embedded into another program but get same results.  No errors are being thrown in the MC3 Error Log.  Not sure where to go from here.

**Comment by culvr** [comment]
Dean,

I finally had a chance to take a look a this. It appears that the HttpsClient is rejecting the SSL certificate from api.prowlapp.com

I didn't have any luck manually installing the Let's Encrypt root/intermediate certificates. Not ideal, but I was able to get it working by setting the property PeerVerification=false in the HttpsClient.

I will push some of those changes soon..Thanks.

**Comment by culvr** [comment]
See:
https://github.com/culvr/ProwlSimplSharp/releases/tag/v1.1.0

**Comment by ddetton** [comment]
Just tested the new Prowl on a CP3 and an MC3 with success.  Thank you for taking the time to look into this and come up with a solution.  It is appreciated!

**Comment by culvr** [comment]
Update:

On August 20, 2017 Prowlapp updated its' SSL configuration to require SNI. https://twitter.com/prowlapp/status/899179309293641728

Crestron's HTTP library is built with .NET 3.5 CF, which does not support SNI. Disabling PeerVerification provided a workaround.

On August 25, 2016 Prowlapp reverted back to the previous SSL config, without SNI: https://twitter.com/prowlapp/status/900961723334524928

I tested the previous version of this module, and it appeared to be working again.
